### ISSUE TITLE
Should we use state or route to keep the steps and answers

### ISSUE THREAD

**Issue by zhang4952** [osulp/dcwizard#6]

**Comment by luisgreg99** [comment]
I think another option would be to consider using an existing wizard component or plugin to handle the flow of steps. 

Here's an example using react-stepzilla (react based component that implements a multi-step form):

- Github: https://github.com/newbreedofgeek/react-stepzilla
- Live demo of react-stepzilla at https://newbreedofgeek.github.io/react-stepzilla/

**Comment by sammysamx20** [comment]
@luisgreg99 We were thinking about using a template or example like react-stepzilla, however, this doesn't really work for our application because stepzilla uses already set amount of steps with only a next button. Ours use a yes or no system which can diverge paths very quickly. The paths would be super different from the set paths the stepzilla library provides.

**Comment by luisgreg99** [comment]
@sammysamx20 In that case, I think we could also create a sate machine to coordinate the transitions between the screens. Here's an example of a wizard that uses a state machine (the next step in the form depends on the user's input at each screen, so each transition could take different paths): https://geetotes.github.io/acme-insurance-quotes/ Here's the source code of the example: https://github.com/geetotes/acme-insurance-quotes/blob/master/src/StateMachine.js

**Comment by sammysamx20** [comment]
Currently, I am trying to keep the steps by states.

**Comment by sammysamx20** [comment]
I am keeping the steps using sessionstorage https://developer.mozilla.org/en-US/docs/Web/API/Storage
